# Generated by Django 3.2.2 on 2021-05-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='repo',
            field=models.CharField(max_length=255),
        ),
    ]
